# Generated by Django 5.0 on 2024-04-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OT_Scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(max_length=15),
        ),
    ]
