# Generated by Django 5.0 on 2024-04-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OT_Scheduling', '0003_alter_ots_department_alter_ots_ot_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='doctor_name',
            field=models.CharField(max_length=1000),
        ),
    ]
