# Generated by Django 5.0 on 2024-04-22 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OT_Scheduling', '0006_alter_procedures_estimated_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoring',
            name='ot_id',
        ),
        migrations.RemoveField(
            model_name='scheduled_surgeries',
            name='doctor_id',
        ),
        migrations.RemoveField(
            model_name='scheduled_surgeries',
            name='ot_id',
        ),
        migrations.RemoveField(
            model_name='scheduled_surgeries',
            name='patient_id',
        ),
        migrations.RemoveField(
            model_name='scheduled_surgeries',
            name='procedure_id',
        ),
        migrations.AddField(
            model_name='monitoring',
            name='ot_number',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='scheduled_surgeries',
            name='department',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='scheduled_surgeries',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='scheduled_surgeries',
            name='mrd',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='scheduled_surgeries',
            name='ot_number',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='scheduled_surgeries',
            name='patient_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='scheduled_surgeries',
            name='procedure_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='scheduled_surgeries',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
