# Generated by Django 5.0 on 2024-04-25 03:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OT_Scheduling', '0008_alter_scheduled_surgeries_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoring',
            name='estimated_duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monitoring',
            name='procedure_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monitoring',
            name='scheduled_surgery_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OT_Scheduling.scheduled_surgeries'),
        ),
        migrations.AlterField(
            model_name='monitoring',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
