# Generated by Django 5.0.4 on 2024-05-24 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OT_Scheduling', '0011_patients_registration_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTstaff',
            fields=[
                ('ot_staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('ot_staff_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('ot_staff_department', models.CharField(blank=True, max_length=1000, null=True)),
                ('ot_staff_designation', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='scheduled_surgeries',
            name='ot_staff_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OT_Scheduling.otstaff'),
        ),
    ]
