# Generated by Django 5.0 on 2024-04-17 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('doctor_name', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OTs',
            fields=[
                ('ot_id', models.AutoField(primary_key=True, serialize=False)),
                ('ot_number', models.IntegerField()),
                ('department', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('mrd', models.IntegerField()),
                ('gender', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Procedures',
            fields=[
                ('procedure_id', models.AutoField(primary_key=True, serialize=False)),
                ('procedure_name', models.TextField()),
                ('department', models.CharField(max_length=50)),
                ('estimated_duration', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('user_type', models.CharField(default='Patient', max_length=15)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Scheduled_Surgeries',
            fields=[
                ('scheduled_surgery_id', models.AutoField(primary_key=True, serialize=False)),
                ('surgery_date', models.DateField(blank=True, null=True)),
                ('surgery_start_time', models.TimeField(blank=True, null=True)),
                ('surgery_end_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OT_Scheduling.doctors')),
                ('ot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OT_Scheduling.ots')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OT_Scheduling.patients')),
                ('procedure_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OT_Scheduling.procedures')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Monitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surgery_date', models.DateField(blank=True, null=True)),
                ('patient_received_in_pre_op_time', models.TimeField(blank=True, null=True)),
                ('antibiotic_prophylaxis_time', models.TimeField(blank=True, null=True)),
                ('patient_wheel_in_OT', models.TimeField(blank=True, null=True)),
                ('induction_start_time', models.TimeField(blank=True, null=True)),
                ('induction_end_time', models.TimeField(blank=True, null=True)),
                ('painting_and_draping_start_time', models.TimeField(blank=True, null=True)),
                ('painting_and_draping_end_time', models.TimeField(blank=True, null=True)),
                ('incision_in_time', models.TimeField(blank=True, null=True)),
                ('incision_close_time', models.TimeField(blank=True, null=True)),
                ('extubation_time_in_OT', models.TimeField(blank=True, null=True)),
                ('wheeled_out_time_to_Post_op_ICU', models.TimeField(blank=True, null=True)),
                ('wheeled_out_from_Post_OP', models.TimeField(blank=True, null=True)),
                ('ot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OT_Scheduling.ots')),
                ('scheduled_surgery_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OT_Scheduling.scheduled_surgeries')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
