# Generated by Django 5.0 on 2024-04-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OT_Scheduling', '0002_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ots',
            name='department',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ots',
            name='ot_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
