# Generated by Django 5.0 on 2024-04-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OT_Scheduling', '0004_alter_doctors_doctor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='department',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='mrd',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='procedures',
            name='estimated_duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='procedures',
            name='procedure_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
