# Generated by Django 5.0 on 2024-04-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OT_Scheduling', '0005_alter_doctors_department_alter_doctors_doctor_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedures',
            name='estimated_duration',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
