# Generated by Django 5.0 on 2024-04-22 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OT_Scheduling', '0007_remove_monitoring_ot_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduled_surgeries',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
