# Generated by Django 5.0 on 2024-04-29 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OT_Scheduling', '0009_monitoring_estimated_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoring',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='scheduled_surgeries',
            name='surgery_type',
            field=models.CharField(blank=True, default='Pre-planned', max_length=1000, null=True),
        ),
    ]
