# Generated by Django 5.0 on 2024-05-03 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OT_Scheduling', '0010_monitoring_doctor_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='registration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
