# Generated by Django 4.2.9 on 2026-09-07 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OT_Scheduling', '0012_otstaff_scheduled_surgeries_ot_staff_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduled_surgeries',
            name='surgery_type',
        ),
        migrations.AddField(
            model_name='monitoring',
            name='nurse_tl',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='monitoring',
            name='ot_staff_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OT_Scheduling.otstaff'),
        ),
        migrations.AddField(
            model_name='monitoring',
            name='special_equipment',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='monitoring',
            name='surgery_type',
            field=models.CharField(blank=True, default='Pre-planned', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='monitoring',
            name='technician_tl',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='otstaff',
            name='ot_staff_employee_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='scheduled_surgeries',
            name='doctor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OT_Scheduling.doctors'),
        ),
        migrations.AddField(
            model_name='scheduled_surgeries',
            name='nurse_tl',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='scheduled_surgeries',
            name='ot_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OT_Scheduling.ots'),
        ),
        migrations.AddField(
            model_name='scheduled_surgeries',
            name='patient_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OT_Scheduling.patients'),
        ),
        migrations.AddField(
            model_name='scheduled_surgeries',
            name='procedure_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OT_Scheduling.procedures'),
        ),
        migrations.AddField(
            model_name='scheduled_surgeries',
            name='special_equipment',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='scheduled_surgeries',
            name='technician_tl',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(max_length=20),
        ),
    ]
