# Generated by Django 4.2.9 on 2026-09-07 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    # Depends on 0012 directly, not 0013 (pre-existing model drift unrelated to this
    # migration, and already broken independent of this change - see
    # docs/confirmation-screen-population-issues.md). Keeps this migration applicable on its
    # own regardless of whether/how 0013 gets fixed.
    dependencies = [
        ('OT_Scheduling', '0012_otstaff_scheduled_surgeries_ot_staff_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('aliases', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='department',
        ),
        migrations.RemoveField(
            model_name='procedures',
            name='department',
        ),
        migrations.AddField(
            model_name='doctors',
            name='emp_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='procedures',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='doctors',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='doctors', to='OT_Scheduling.department'),
        ),
        migrations.AddField(
            model_name='procedures',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='procedures', to='OT_Scheduling.department'),
        ),
    ]
