# Generated by Django 4.2.9 on 2026-09-07 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OT_Scheduling', '0013_preexisting_model_drift'),
        ('OT_Scheduling', '0014_add_department_model'),
    ]

    operations = [
    ]
